version: '3.5'

services:
    nginx:
        container_name: nginx
        build: ./nginx/.
        ports:
            - "1234:80"

    mariadb:
        container_name: mariadb
        build: ./mariadb/.
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: hola


